### ISSUE TITLE
Jack should now work - anything else needed to be fixed in the Termux packages?

### ISSUE THREAD

**Issue by fornwall** [4544fa8d/AndroTermux#1]
Hi, the jack package should now work again after being broken for quite some time.

Is there anything else you need to have fixed or added to Termux packages for this? Seems interesting!

**Comment by 4544fa8d** [comment]
Hello there :)

I've tried updating my project but unfortunately encountered other error with aapt.

Always when I want to build  test app with make debug i get error:

...
applyFileOverlay for mipmap
       (new resource id main from ./res/layout/main.xml)

It looks like aapt can't generate id for widget in main.xml.

I'm sure this is problem with Termux aapt version because I can build this project without problems on my Ubuntu PC.

There is also mater of 3 additional programs needed for building basic APK:
- jarsigner - for signing APK with debug and release keys
- jar - for adding classes.dex to APK packages (probably could replace it with zip)
- zipalign - for building nice release APK's

**Comment by fornwall** [comment]
@4544fa8d Can you try updating to the latest aapt version with `apt update && apt upgrade` and see if that fixes the aapt issue?

> jar - for adding classes.dex to APK packages (probably could replace it with zip)

As jar is a bit heavyweight (implemented in java) and zip is already available, I think zip is the best way at least for now. Try changing

```
jar -uf ./bin/$(APP_NAME).unsigned.apk -C ./obj classes.dex
```

to something like

```
cd obj && zip -u ../bin/$(APP_NAME).unsigned.apk classes.dex
```

> jarsigner - for signing APK with debug and release keys
> zipalign - for building nice release APK's

I've just added a new package, `apksigner`, which serves as a lightweight replacement for both of these tools. Install with `apt install apksigner`, then run as

```
apksigner [-p password] keystore input-apk output-apk
```

Here the key password defaults to "android" if not specified, and the specified keystore file is created if one does not exist for easy usage. Try it out and let me know how it works!

**Comment by fornwall** [comment]
About aapt: I've just added a patch to the package to add a default platform package (`-I`), so the `-I ./lib/android.jar` flag can now be removed as well as the `./lib/android.jar`.

**Comment by 4544fa8d** [comment]
I've successfully built and installed project on my Motorolla so I will say that version 0.1 of AndroTermux is ready.

Thanks for all your help :)
